[package]
name = "clipboard_pasta_nif"
version = "0.1.0"
authors = []
edition = "2018"

[lib]
name = "clipboard_pasta_nif"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.23.0"
copypasta = "0.7.1"
